### ISSUE TITLE
Delegation, Group ACLs, and confused deputy

### ISSUE THREAD

**Issue by Stebalien** [solid/solid#28] opened 2016-01-20 21:14 UTC
As far as I can tell (untested and I'm not too familiar with the protocol), there's a confused deputy issue with how delegation and groups are handled that allows users without read access to the group definition to determine if a user is in a group.

Given:

Alice = Server A's owner
Bob = Server B's owner
Malory = An attacker who owns a file on servers A and B.
Club = A group managed by Bob

Malory defines a group Attackers with her as the sole member and overwrites her file on server B with this new group definition and changes the ACL to give the Club group read access. Malory then changes the ACL of her file on server A to only allow reads by the Attackers group. Malory then attempts to fetch the file from server A verifying that Alice is a member of the Club group.

The problem is that server A has the power to act as Alice but shouldn't be doing so in this case.

**Comment by dmitrizagidulin** [comment] 2016-01-21 20:53
@Stebalien - can you by any chance post the actual example ACL files for this scenario?

**Comment by nicola** [comment] 2016-01-22 04:25
ServerA

ACLs
```
</> <owner> <Alice>
</malory-file-a> <owner> <Malory>
```

Server B

ACLs
```
</> <owner> <Bob>
</malory-file-b> <owner> <Malory>
</club> <owner> <Bob>
```

Now Malory creates a group called attacker inside /malory-file-a, and gives the Club access to this file:

Server A
```
</malory-file-a> <owner> <Attackers>
```

Now from Server A fetches a file from server A trying to verify that Alice is member of the Club
(I lost you here)

What do you mean by "act as Alice"? Are groups private in your case?

**Comment by Stebalien** [comment] 2016-01-22 15:03
@nicola,
> What do you mean by "act as Alice"?

I mean that Alice has delegated authority to her server (server A). Given the problem in #8, I'm assuming that server A has the ability to authenticate on behalf of Alice. Is this not the case?

>  Are groups private in your case?

Yes. Specifically, Attackers is defined in `https://server-b.com/malory-file-b#Attackers` so yes, it's private and only readable by Club. Club is also private and only readable by Bob (and server B).

---

Just to be clear, the Access control on Malory's file on server A would be:

```
</malory-file-a> <owner> <https://server-b.com/malory-file-b#Attackers>
```

(It refers to attackers as defined on server A).

**Comment by bblfish** [comment] 2016-01-30 13:05
It would be helpful if the examples were written out using the documented and implemented [web access control ontology](https://www.w3.org/wiki/WebAccessControl). There is no relation `owner` there currently, so these examples need a huge amount of interpretation as they stand.

**Comment by Stebalien** [comment] 2016-01-30 14:08
@bblfish 

# Starting State:

## Pieces

Server A = A server.
Server B = A server.
Malory = The attacker.
Mancy = The attacker's alt account (makes things simpler).
Alice = The owner of server A.
Bob = The owner of server B.
Club = A secret group, controlled by Bob, whose members are Alice and Bob.

## Objective

Malory wants to know if Alice is a member of Club

## Server A:

```
[acl:accessTo </>; <acl:agent> <Alice>; acl:mode acl:Control].
[acl:accessTo </malory-file-a>; <acl:agent> <Malory>; acl:mode acl:Control].
```

## Server B:

ACLs:

```
[acl:accessTo </>; <acl:agent> <Bob>; acl:mode acl:Control]
[acl:accessTo </malory-file-b>; <acl:agent> <Malory>; acl:mode acl:Control]
[acl:accessTo </club>; <acl:agent> </club#Club>; acl:mode acl:Read]
```

Club (`http://server-b.com/club`):

```
<#Club> a foaf:Group;
<#Club> <foaf:member> <Alice>
<#Club> <foaf:member> <Bob>
```

# Step 1

Malory creates an attackers group by adding the following to `http://server-a.com/malory-file-b`:

```
<#Attackers> a foaf:Group;
<#Attackers> <foaf:member> <Mancy>
```

# Step 2

Malory allows members of Club to read the Attackers group file by adding the following to the ACL:

```
[acl:accessTo </malory-file-b>; <acl:agent> </club#Club>; acl:mode acl:Control]
```

# Step 3

Malory then allows anyone in the Attackers group to access `http://server-a.com/malory-file-a` by adding the following ACL to Server A:

```
[acl:accessTo </malory-file-a>; <acl:agent> <http://server-b.com/malory-file-b#Attackers>; acl:mode acl:Control].
```

# Step 4

Malory logs out and logs back in as Mancy and tries to access `http://server-a.com/malory-file-a`. If she is successful, Alice must be in the Club group because her server was able to read the Attackers group definition.

**Comment by bblfish** [comment] 2016-01-30 15:52
Thanks. I am not so sure what `acl:Control` means so I opened an issue on that [acl:Control](https://github.com/solid/solid/issues/51). I'll think about using the pattern specified there.

The problem is giving Malory write access to the acls on server b, which I suppose is what the second line of this is mean to mean:

```
[acl:accessTo </>; <acl:agent> <Alice>; acl:mode acl:Control].
[acl:accessTo </malory-file-a>; <acl:agent> <Malory>; acl:mode acl:Control].
```

(I don't really like the idea of specifying the editing of an acl file via another file. see issue 51)

In which case it is not really an attack on acls: the problem is server B giving rights to someone they should not have access. Ie at that point its a social problem, not an acl problem.

**Comment by Stebalien** [comment] 2016-01-30 16:02
Actually, I don't believe that solid uses `acl:Control`. IIRC, it just sets read/write access on the ACL file itself:

```
[acl:accessTo </,acl>; <acl:agent> <Alice>; acl:mode acl:Read, acl:Write].
```

But that's not really relevant.

With regards to your comment, it's perfectly reasonable to give someone the right to set ACLs on their own file, regardless of where it's stored. The problem here is that Malory is able to abuse the rights that Alice delegated to her server.

**Comment by bblfish** [comment] 2016-01-30 16:17
What you have left out of your explanation is the information of the links from the files to their acls. This is very important part of WAC. The server (and authorized clients) can only tell what acl applies to a resource by following the `Link: <doc.acl>; rel="acl"` relation found in the header of that resource. ACLs by themselves don't give permissions. So again its a bit difficult to interpret your examples.

This acl seeems to set the rights for the LDP Container `</>` to only allow Alice to read and write to the acl.

```Turtle
[acl:accessTo </,acl>; <acl:agent> <Alice>; acl:mode acl:Read, acl:Write].
```
How do you now translate the other acl which gives Malory access? Like this?

```Turtle
[acl:accessTo </malory-file-a,acl>; <acl:agent> <Malory>; acl:mode acl:Read, acl:Write ].
```

This would indeed only give malory rights to edit the acl for her own file  `<malory-file-a>`  by editing
`<malory-file-a.acl>` . She would not there be able to increase the number of people who can view that file, and edit that acl, but she would not be able to edit `</,acl>` from this information alone at least.

Of course if you

**Comment by Stebalien** [comment] 2016-01-30 16:34
That's why I used control as it makes ownership clear. For the sake of *this* discussion, assume that anyone with the `acl:Control` permission can read and write a file and modify the ACLs of the file.

**Comment by nicola** [comment] 2016-01-30 16:37
I haven't read the entire conversation yet.
We do use acl:Control to specify who has read and write for the ACL of a resource (containers included)

**Comment by bblfish** [comment] 2016-01-30 17:12
Perhaps this is a good reason not to use `acl:Control` then. Rww-play gets one fine without it, it seems to me: See [issue 51](https://github.com/solid/solid/issues/51)

**Comment by dmitrizagidulin** [comment] 2016-01-30 17:30
> Malory creates an attackers group by adding the following to `http://server-a.com/malory-file-b`:

@Stebalien - in Step 1, with the ACLs that you have set up, Alice doesn't have Write access to `/` on server-a. So, she cannot create `http://server-a.com/malory-file-b`.

**Comment by Stebalien** [comment] 2016-01-30 17:41
@dmitrizagidulin Sorry, that should have been `server-b.com`. I've updated the comment.

**Comment by dmitrizagidulin** [comment] 2016-01-30 18:21
Incidentally, the current meaning of `acl:Control` is in flux. The vocabulary, https://www.w3.org/ns/auth/acl defines it to mean "Allows read/write access to the ACL for the resource(s)".
But the [WAC Wiki page](https://www.w3.org/wiki/WebAccessControl), in the Modes of Access table, defines it as "Those allowed it may set the Access Control List for this themselves." Basically, meaning that `acl:Control` means "You can edit the ACL for this resource".

But it looks like you're just using it to mean Read+Write access in this example, no problem.

> Malory logs out and logs back in as Mancy and tries to access `http://server-a.com/malory-file-a`. If she is successful, Alice must be in the Club group because her server was able to read the Attackers group definition.

The conclusion in Step 4 doesn't follow. I think you may be conflating the capabilities of Alice and her server, `server-a.com`.

If Mancy tries to access `http://server-a.com/malory-file-a`, here's what happens. The server first looks for the ACL for 'file a' (the acl-prefix is specified by the server, but is usually something like `.acl`), `malory-file-a.acl`. This is where I assume the server would find your entries that you specify:

```
[acl:accessTo </malory-file-a>; <acl:agent> <Malory>; acl:mode acl:Control].
[acl:accessTo </malory-file-a>; <acl:agent> <http://server-b.com/malory-file-b#Attackers>; acl:mode acl:Control].
```

Since Mancy doesn't fit the first statement (about Malory), the server would fetch `http://server-b.com/malory-file-b#Attackers`, to see if Mancy maybe fits *that* permission. Now, here's the interesting part. Server A is requesting `malory-file-b` either *as* or *on behalf of* Mancy. That is, using Mancy's credentials.

`malory-file-b` contains the following:

```
<#Attackers> a foaf:Group;
<#Attackers> <foaf:member> <Mancy>
```

Assuming the ACL of `malory-file-b` allows Mancy read access to it, Server B would return that ACL to the requesting Server A. Server A would see that, indeed, Mancy is a member of the Attackers group, which means they would have access to `http://server-a.com/malory-file-a`.
Access would be granted to Mancy.

And yet nothing whatsoever is revealed about Alice, or her membership to the club.

**Comment by Stebalien** [comment] 2016-01-30 18:42
> But the WAC Wiki page, in the Modes of Access table, defines it as "Those allowed it may set the Access Control List for this themselves." Basically, meaning that acl:Control means "You can edit the ACL for this resource".

I'm using this definition. Being able to edit the ACL implies being able to read/write the resource.

> Server A is requesting malory-file-b either as or on behalf of Mancy. That is, using Mancy's credentials.

That's not how delegation could ever work; no one would ever delegate privileges to someone else's server. I'm assuming a scenario like that in #8 is possible. If Alice's server can't act on behalf of Alice in this case, then #8 is trivially solved by including an "I have no permissions" header in the server to server request.

**Comment by dmitrizagidulin** [comment] 2016-01-30 18:52
> Being able to edit the ACL implies being able to read/write the resource.

`acl:Control` doesn't *directly* imply read/write access. Being able to edit the ACL only implies that an agent can *change* the ACL to grant themselves read/write access. Which is a subtle difference.

> That's not how delegation could ever work

So, I'm not sure whether the current Solid servers actually implement WAC delegation (I know that support for ACL groups is currently disabled in LDNode, pending some further sorting out).

But the *intended* delegation protocol does work like that. Take a look at the [Extending the WebID Protocol with Access Delegation](http://bblfish.net/tmp/2012/08/05/WebID_Delegation.pdf) paper, for the explanation of the mechanism.

In any case, Alice's server would *not* be using Alice's credentials in any of the interactions in this scenario.
It would either use its *own* credentials (that would identify it as Server A, not as Alice), or it would use Malory's.

**Comment by dmitrizagidulin** [comment] 2016-03-21 11:51
Closing this. (Feel free to reopen if you have further questions).

**Closed by dmitrizagidulin** 2016-03-21 11:51 UTC
Labels: help wanted, question
